accounts/urls.py
from django.urls import path

from .views import account_home_page, login_page, logout_page, register_page, address_create_view, update_profile
from orders.views import order_history_page
from analytics.views import user_product_history

app_name = 'account'

urlpatterns = [
    path('home/', account_home_page, name='account-home'),
    path('login/', login_page, name='login'),
    path('logout/', logout_page, name='logout'),
    path('register/', register_page, name='register'),
    path('address/create/view/', address_create_view, name='address_create_view'),
    path('order/history', order_history_page, name='order_history'),
    path('user/history', user_product_history, name='user_history'),
    path('user/profile/update/', update_profile, name='update_profile'),
]

carts/urls.py
from django.urls import path

from .views import cart_home, cart_update, checkout_home, checkout_success, payment_page_view

app_name = 'cart'

urlpatterns = [
    path('', cart_home, name='home'),
    path('update/', cart_update, name='update'),
    path('checkout/', checkout_home, name='checkout'),
    path('success/', checkout_success, name='success'),
    path('payment/online/', payment_page_view, name='payment_page'),

]

eComm/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from .views import home_page, contact_page
from products.views import search_product 
from analytics.views import (
    sales_view, 
    sales_ajax_view, 
    last_week_sales_view, 
    three_week_sales_view, 
    four_week_sales_view,
    product_analytics_view, 
    customers_analytics_view, 
    advertise_product_view
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name='home'),
    path('contact/', contact_page, name='contact'),
    path('search/', search_product, name='search'),
    path('products/', include('products.urls', namespace='products')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='order')),
    path('account/', include('accounts.urls', namespace='account')),
    path('analytics/sales/this-week/', sales_view, name="this-week-sales-analytics"),
    path('analytics/sales/last-week/', last_week_sales_view, name="last-week-sales-analytics"),
    path('analytics/sales/three-weeks-ago/', three_week_sales_view, name="three-week-sales-analytics"),
    path('analytics/sales/four-week-ago/', four_week_sales_view, name="four-week-sales-analytics"),
    path('analytics/sales/data/', sales_ajax_view, name="sales-analytics-data"),
    path('analytics/sales/products/', product_analytics_view, name="product-analytics"),
    path('analytics/sales/customer/', customers_analytics_view, name="customer-analytics"),
    path('analytics/sales/product-advertisement/', advertise_product_view, name="product-advertisement"),

]

if settings.DEBUG :
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from .views import product_list, product_detail 

app_name = 'products'

urlpatterns = [
    path('', product_list, name='product-list'),
    path('<str:slug>/', product_detail, name='product-detail'),

]

carts/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import m2m_changed
from django.contrib import messages
from django.shortcuts import redirect

from products.models import Product
# Create your models here.

User = settings.AUTH_USER_MODEL

class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get('cart_id', None)
        qs = Cart.objects.filter(id=cart_id)
        cart_obj = None
        
        if qs.count() == 1:
            cart_obj = qs.first()
            if request.user.is_authenticated and request.user is not None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            if request.user is not None:
                if request.user.is_authenticated:
                    cart_obj = Cart.objects.create(user=request.user)
                    request.session["cart_id"] = cart_obj.id
        return cart_obj

class Cart(models.Model):
    id          = models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    user        = models.ForeignKey(User, on_delete=models.CASCADE)
    products    = models.ManyToManyField(Product, blank=True)
    total       = models.IntegerField(default=0)
    updated     = models.DateTimeField(auto_now=True)
    timestamp   = models.DateTimeField(auto_now_add=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)


def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all()
        total = 0
        for i in products:
            total += i.price
        if instance.total != total:
            instance.total = total
            instance.save()

m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)

carts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages

from .models import Cart
from products.models import Product
from accounts.forms import AddressForm
from accounts.models import BillingProfile, Address
from orders.models import Order

# Create your views here.

def cart_home(request):
    cart_obj = Cart.objects.new_or_get(request=request)
    is_empty = True
    if cart_obj is not None:
        length = len(cart_obj.products.all())
        if length == 0:
            is_empty = True
        else:
            is_empty = False

    context = {
        'cart_obj': cart_obj,
        "is_empty": is_empty
    }
    return render(request, "carts/cart-home.html", context=context)


def cart_update(request):
    if request.user.is_authenticated:
        product_id = request.POST.get('product_id')
        if product_id is not None:
            try:
                product_obj = Product.objects.get_by_id(id=product_id)
            except:
                messages.error(request, "Error Occur!!! Product is gone.")
        else:
            return redirect("product:product-list")

        cart_obj = Cart.objects.new_or_get(request=request)
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)
        else:
            cart_obj.products.add(product_obj)
    else:
        messages.warning(request, "Please Login, before buying a product.")
        return redirect("account:login")

    request.session['cart_items_count'] = cart_obj.products.all().count()
        
    return redirect("cart:home")


def checkout_home(request):
    order_obj = None
    if request.user.is_authenticated:
        cart_obj = Cart.objects.new_or_get(request)
        if cart_obj.products.count() == 0:
            messages.info(request, "Cart is empty now!")
            return redirect("cart:home")
        address_form = AddressForm()

        billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request=request)

        if billing_profile is not None:
            order_obj, order_obj_created = Order.objects.new_or_get(cart_obj=cart_obj, billing_profile=billing_profile)

            billing_address_id = request.session.get('billing_address_id')
            if billing_address_id:
                order_obj.billing_address = Address.objects.get(id=billing_address_id)
                del request.session['billing_address_id']
                order_obj.save()

        if request.method == 'POST':
            if order_obj.check_done():
                if order_obj.payment_method == 'Cash On Delivery':
                    request.session['cart_items_count'] = 0
                    del request.session["cart_id"]
                    return redirect("cart:success")
                else:
                    order_obj.mark_paid()
                    print("Credit or debit selected. go to the online payment page.")
                    return redirect("cart:payment_page")


    else:
        messages.warning(request, "Please login, you cannot access this page.")
        return redirect("account:login")


    context = {
        'address_form': address_form,
        'cart_obj': cart_obj,
        'order_obj': order_obj,
        'billing_profile': billing_profile
    }
    return render(request, "carts/checkout.html", context=context)



def checkout_success(request):
    return render(request, "carts/success-checkout.html", {})


def payment_page_view(request):
    if request.method == 'POST':
        print(request.POST)
        request.session['cart_items_count'] = 0
        del request.session["cart_id"]
        return redirect("cart:success")
    return render(request, "carts/payment-page.html", {})

carts/templates/carts/cart-home.html
{% extends 'base.html' %}

{% block content %}


<div class="container pb-5">
    {% if is_empty %}

    <div class="container p-5">
        <div class="row">
            <div class="col-12 col-md-5 mx-auto">
                <div class="text-center mx-md-auto">
                    <i class="fas fa-cart-arrow-down h1"></i>
                </div>
                <div class="text-center">
                    <h3 class="pb-4">Your Cart is Currently Empty.</h3>
                    <p class="text-center pb-2">Before proceed to checkout you must add some products to your shopping
                        cart. You will find a lot of interesting products on our "Products" page.</p>
                    <a href="{% url 'products:product-list' %}" class="btn btn-primary px-5">Start Shopping</a>
                </div>
            </div>
        </div>
    </div>

    {% else %}

    <h1>Cart: </h1>

    <table class="table table-hover">
        <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Product Name</th>
                <th scope="col">Product Price</th>
            </tr>
        </thead>
        <tbody>
            {% for product in cart_obj.products.all %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{{ product.get_absolute_url }}">{{ product.title }}</a></td>
                <td>{{ product.price }}</td>
            </tr>
            {% endfor %}
            <tr>
                <td colspan="2"></td>
                <td><b>Total : </b> <span> {{ cart_obj.total }} </span></td>
            </tr>
            <tr>
                <td colspan="2"></td>
                <td><a href="{% url 'cart:checkout' %}" class="btn btn-success">Checkout</a></td>
            </tr>
        </tbody>
    </table>

    {% endif %}

</div>
{% endblock %}

carts/templates/carts/checkout.html
{% extends 'base.html' %} {% load static %} {% block title %} Checkout Page {% endblock %} {% block content %}

<div class="container">
    <div class="py-5 text-center">
        <img class="d-block mx-auto mb-4" src="{% static 'imgs/checkout.png' %}" alt="Checkout Logo" width="120" height="120">
        <h1>Checkout Page</h1>
        <hr>
    </div>

    <div class="row">
        {% if not order_obj.billing_address %}
        <div class="col-md-8 border p-4">
            <h4 class="mb-3">Billing Address</h4>
            <hr>
            <form method="POST" action="{% url 'account:address_create_view' %}">
                {% csrf_token %} {{ address_form.as_p }}

                <hr class="mb-4">

                <h4 class="mb-3">Payment</h4>

                <div class="d-block my-3">
                    <div class="custom-control custom-radio">
                        <input id="cod" name="payment_method" value="Cash On Delivery" type="radio" class="custom-control-input" checked required>
                        <label class="custom-control-label" for="paypal">Cash On Delivery</label>
                    </div>
                    <div class="custom-control custom-radio">
                        <input id="credit" name="payment_method" value="Credit card" type="radio" class="custom-control-input" required>
                        <label class="custom-control-label" for="credit">Credit card</label>
                    </div>
                    <div class="custom-control custom-radio">
                        <input id="debit" name="payment_method" value="Debit card" type="radio" class="custom-control-input" required>
                        <label class="custom-control-label" for="debit">Debit card</label>
                    </div>
                </div>

                <hr class="mb-4">
                <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>
            </form>
        </div>
        {% else %}
        <div class="col-md-8 border p-4">
            <h3 class="mb-3">Finalize Checkout</h3>
            <hr>
            <table class="table table-bordered">
                <tbody>
                    <tr>
                        <td><b>Order ID: </b></td>
                        <td> {{ order_obj.order_id }} </td>
                    </tr>
                    <tr>
                        <td><b>Your Email ID: </b></td>
                        <td> {{ order_obj.billing_profile }} </td>
                    </tr>
                    <tr>
                        <td><b>Billing Address: </b></td>
                        <td> {{ order_obj.billing_address.get_address }} </td>
                    </tr>
                    <tr>
                        <td><b>Order Total: </b></td>
                        <td> {{ order_obj.total }} </td>
                    </tr>
                    <tr>
                        <td><b>Payment Method: </b></td>
                        <td> {{ order_obj.payment_method }} </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <form method="POST">
                                {% csrf_token %}
                                <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to
                                    checkout</button>
                            </form>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        {% endif %}
        <div class="col-md-4 mb-4">
            <h4 class="d-flex justify-content-between align-items-center mb-3">
                <span class="text-muted">Your cart</span>
                <span class="badge badge-secondary badge-pill"> {{ request.session.cart_items_count }} </span>
            </h4>
            <ul class="list-group mb-3">
                {% for product in cart_obj.products.all %}
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                    <div>
                        <h6 class="my-0">{{ product }}</h6>
                    </div>
                    <span class="text-muted">${{ product.price }}</span>
                </li>
                {% endfor %}

            </ul>

            <ul class="list-group mb-3 py-2">
                <li class="list-group-item d-flex justify-content-between">
                    <span>Cart Total</span>
                    <span>${{ cart_obj.total }}</span>
                </li>
                <li class="list-group-item d-flex justify-content-between">
                    <span>Shipping Cost</span>
                    <span>${{ order_obj.shipping_cost }}</span>
                </li>
                <li class="list-group-item d-flex justify-content-between">
                    <span>Total (USD)</span>
                    <strong>${{ order_obj.total }}</strong>
                </li>
            </ul>
        </div>
    </div>
</div>




{% endblock %}

carts/templates/carts/payment-page.html
{% extends 'base.html' %} {% block title %} Payment Page {% endblock %} {% block content %}

<style>
    .payment-form {
        padding-bottom: 50px;
    }
    
    .payment-form .block-heading {
        padding-top: 50px;
        margin-bottom: 40px;
        text-align: center;
    }
    
    .payment-form .block-heading p {
        text-align: center;
        max-width: 420px;
        margin: auto;
        opacity: 0.7;
    }
    
    .payment-form .block-heading h2 {
        margin-bottom: 1.2rem;
        color: #3b99e0;
    }
    
    .payment-form form {
        border-top: 2px solid #5ea4f3;
        background-color: #ffffff;
        max-width: 600px;
        margin: auto;
    }
    
    .payment-form .title {
        font-size: 1em;
        border-bottom: 1px solid rgba(0, 0, 0, 0.1);
        margin-bottom: 0.8em;
        font-weight: 600;
        padding-bottom: 8px;
    }
    
    .payment-form .card-details {
        padding: 25px 25px 15px;
    }
    
    .payment-form .card-details label {
        font-size: 12px;
        font-weight: 600;
        margin-bottom: 15px;
        color: #79818a;
        text-transform: uppercase;
    }
    
    .payment-form .card-details button {
        margin-top: 0.6em;
        padding: 12px 0;
        font-weight: 600;
    }
    
    .payment-form .date-separator {
        margin-left: 10px;
        margin-right: 10px;
        margin-top: 5px;
    }
</style>

<section class="payment-form">
    <div class="container">
        <div class="block-heading">
            <h2>Payment - Rauf-eComm</h2>
            <p>Your Card Details Will Not Saved to this Website.</p>
        </div>
        <form method="POST" class="shadow-lg">
            {% csrf_token %}
            <div class="card-details">
                <h3 class="title">Credit Card Details</h3>
                <div class="row">
                    <div class="form-group col-sm-7">
                        <label for="card-holder">Card Holder</label>
                        <input id="card-holder" name="card-holder" type="text" class="form-control" placeholder="Card Holder" required>
                    </div>
                    <div class="form-group col-sm-5">
                        <label for="expiration-date">Expiration Date</label>
                        <div class="input-group expiration-date">
                            <input type="text" name="expiration-date" class="form-control" placeholder="MM" required>
                            <span class="date-separator">/</span>
                            <input type="text" name="expiration-date" class="form-control" placeholder="YYYY" required>
                        </div>
                    </div>
                    <div class="form-group col-sm-8">
                        <label for="card-number">Card Number</label>
                        <input id="card-number" type="text" class="form-control" placeholder="Card Number" name="card-number" required>
                    </div>
                    <div class="form-group col-sm-4">
                        <label for="cvc">CVC</label>
                        <input id="cvc" name="cvc" type="password" class="form-control" placeholder="CVC" required>
                    </div>
                    <div class="form-group col-sm-12">
                        <button type="submit" class="btn btn-primary btn-block">Proceed</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>
{% endblock %}

carts/templates/carts/success-checkout.html
{% extends 'base.html' %}
{% block title %} Success Page {% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-6 col-12 mx-auto text-center p-5 m-5">
            <h1 class="display-2">Thank You for Your Order.</h1>
        </div>
        <div class="col-12">
            <hr>
        </div>
        <div class="col-12 mx-auto text-center p-4">
            <h6>Goto <a href="{% url 'account:account-home' %}">Account Home</a> Page.</h6>
        </div>
    </div>
</div>

{% endblock %}