accounts/urls.py
from django.urls import path

from .views import account_home_page, login_page, logout_page, register_page, address_create_view, update_profile
from orders.views import order_history_page
from analytics.views import user_product_history

app_name = 'account'

urlpatterns = [
    path('home/', account_home_page, name='account-home'),
    path('login/', login_page, name='login'),
    path('logout/', logout_page, name='logout'),
    path('register/', register_page, name='register'),
    path('address/create/view/', address_create_view, name='address_create_view'),
    path('order/history', order_history_page, name='order_history'),
    path('user/history', user_product_history, name='user_history'),
    path('user/profile/update/', update_profile, name='update_profile'),
]

carts/urls.py
from django.urls import path

from .views import cart_home, cart_update, checkout_home, checkout_success, payment_page_view

app_name = 'cart'

urlpatterns = [
    path('', cart_home, name='home'),
    path('update/', cart_update, name='update'),
    path('checkout/', checkout_home, name='checkout'),
    path('success/', checkout_success, name='success'),
    path('payment/online/', payment_page_view, name='payment_page'),

]

eComm/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from .views import home_page, contact_page
from products.views import search_product 
from analytics.views import (
    sales_view, 
    sales_ajax_view, 
    last_week_sales_view, 
    three_week_sales_view, 
    four_week_sales_view,
    product_analytics_view, 
    customers_analytics_view, 
    advertise_product_view
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name='home'),
    path('contact/', contact_page, name='contact'),
    path('search/', search_product, name='search'),
    path('products/', include('products.urls', namespace='products')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='order')),
    path('account/', include('accounts.urls', namespace='account')),
    path('analytics/sales/this-week/', sales_view, name="this-week-sales-analytics"),
    path('analytics/sales/last-week/', last_week_sales_view, name="last-week-sales-analytics"),
    path('analytics/sales/three-weeks-ago/', three_week_sales_view, name="three-week-sales-analytics"),
    path('analytics/sales/four-week-ago/', four_week_sales_view, name="four-week-sales-analytics"),
    path('analytics/sales/data/', sales_ajax_view, name="sales-analytics-data"),
    path('analytics/sales/products/', product_analytics_view, name="product-analytics"),
    path('analytics/sales/customer/', customers_analytics_view, name="customer-analytics"),
    path('analytics/sales/product-advertisement/', advertise_product_view, name="product-advertisement"),

]

if settings.DEBUG :
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
# Create your models here.

User = settings.AUTH_USER_MODEL

class BillingProfileManager(models.Manager):
    def new_or_get(self, request):
        obj = None 
        created = False
        user = request.user
        if user.is_authenticated:
            obj, created = self.model.objects.get_or_create(user=user, email=user.email)
        return obj, created

class BillingProfile(models.Model):
    user        = models.OneToOneField(User, on_delete=models.CASCADE)
    email       = models.EmailField()
    updated     = models.DateTimeField(auto_now=True)
    timestamp   = models.DateTimeField(auto_now_add=True)

    objects = BillingProfileManager()

    def __str__(self):
        return self.email

def post_save_email_receiver(sender, instance, created, *args, **kwargs):
    if created and instance.email:
        BillingProfile.objects.get_or_create(user=instance, email=instance.email)

post_save.connect(post_save_email_receiver, sender=User)

###########################################################################################################

class AddressManager(models.Manager):
    pass

class Address(models.Model):
    billing_profile  = models.ForeignKey(BillingProfile, null=True, on_delete=models.CASCADE)
    address_line1   = models.CharField(max_length=120)
    address_line2   = models.CharField(max_length=120, null=True, blank=True)
    city            = models.CharField(max_length=120)
    state           = models.CharField(max_length=120)
    country         = models.CharField(max_length=120)
    pincode         = models.CharField(max_length=120)

    objects = AddressManager()

    def __str__(self):
        return str(self.billing_profile)

    def get_address(self):
        return f"{self.address_line1} {self.address_line2}, {self.city}, {self.state}, {self.country}, {self.pincode}"

accounts/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Address



class LoginForm(forms.Form):
    username    = forms.CharField(widget=forms.TextInput(
        attrs = {
            'class': "form-control",
            'placeholder': "Username",
        }
    ))
    password    = forms.CharField(widget=forms.PasswordInput(
        attrs = {
            'class': "form-control",
            'placeholder': "Password",
        }
    ))


class RegisterForm(forms.Form):
    username    = forms.CharField(widget=forms.TextInput(
        attrs = {
            'class': "form-control",
            'placeholder': "Username",
        }
    ))
    email       = forms.EmailField(widget=forms.EmailInput(
        attrs= {
            'class': "form-control",
            'placeholder': "Email",
        }
    ))
    password    = forms.CharField(widget=forms.PasswordInput(
        attrs = {
            'class': "form-control",
            'placeholder': "Password",
        }
    ))
    password2   = forms.CharField(label= "Confirm Password", widget=forms.PasswordInput(
        attrs = {
            'class': "form-control",
            'placeholder': "Confirm Password",
        }
    ))


    def clean_email(self):
        email = self.cleaned_data.get("email")
        if not "gmail.com" in email:
            raise forms.ValidationError("Email has to be gamil.com")
        return email

    def clean(self):
        data = self.cleaned_data
        password = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")
        if password != password2:
            raise forms.ValidationError("Password must match.")
        return data


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['address_line1', 'address_line2', 'city', 'state', 'country', 'pincode']
        widgets = {
            'address_line1': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'House/Building Name'
                }
            ),
            'address_line2': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Street'
                }
            ),
            'city': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'City Name'
                }
            ),
            'state': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'State Name'
                }
            ),
            'country': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Country Name'
                }
            ),
            'pincode': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Your Postal Code'
                }
            )
        }


class UpdateProfileForm(forms.ModelForm):
    first_name = forms.CharField(label='First Name', required=False, widget=forms.TextInput(
        attrs = {
            'class': "form-control",
            'placeholder': "First Name",
        }
    ))
    last_name = forms.CharField(label='Last Name', required=False, widget=forms.TextInput(
        attrs = {
            'class': "form-control",
            'placeholder': "Last Name",
        }
    ))
    class Meta:
        model = User
        fields = ['first_name', 'last_name']
        

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('This is not your email')
        return email

accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib import messages

from .forms import LoginForm, RegisterForm, UpdateProfileForm
from accounts.forms import AddressForm
from accounts.models import BillingProfile
from orders.models import Order
from carts.models import Cart
# Create your views here.


def account_home_page(request):
    if not request.user.is_authenticated:
        messages.warning(request, "Please Login. You cannot access this page!")
        return redirect("account:login")
    context = {}
    return render(request, "accounts/account-home.html", context=context)

def login_page(request):
    form = LoginForm(request.POST or None)
    context = {
        'title': "Please Login!", 
        'form': form,
    }
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        print("User Logged in : ", request.user.is_authenticated)
        # Redirect to a success page.
        messages.success(request, "Login Successful.")
        return redirect('/')
    else:
        # Return an 'invalid login' error message.
        print("Error...")
    
    return render(request, 'accounts/login.html', context=context)

def register_page(request):
    form = RegisterForm(request.POST or None)
    context = {
        'title': "Register Yourself", 
        'form': form,
    }
    username = request.POST.get('username')
    email    = request.POST.get('email')
    password = request.POST.get('password')
    if form.is_valid():
        user = User.objects.create_user(username=username, email=email, password=password)
        print("User created : ", user)
        messages.success(request, f"User: - '{user}' successfully Added.")
        print(form.cleaned_data)
    return render(request, 'accounts/register.html', context=context)


def logout_page(request):
    if request.user.is_authenticated:
        print("User logged out : ", request.user)
        messages.success(request, "Logged Out ")
        logout(request)
        return redirect("account:login")
    else:
        messages.error(request, "Logging out failed...")


def address_create_view(request):
    form = AddressForm(request.POST or None)

    if form.is_valid():
        print(request.POST)
        instance = form.save(commit=False)
        billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request=request)
        cart_obj = Cart.objects.new_or_get(request=request)

        if billing_profile is not None:
            order_obj, order_obj_created = Order.objects.new_or_get(cart_obj=cart_obj, billing_profile=billing_profile)
            payment_method = request.POST.get("payment_method", None)
            if payment_method:
                order_obj.payment_method = payment_method
                order_obj.save()
            instance.billing_profile = billing_profile
            instance.save()
            request.session['billing_address_id'] = instance.id
        else:
            messages.error(request, "Might have some problem....!")
            return redirect("cart:checkout")

    return redirect("cart:checkout")


def update_profile(request):
    if request.user.is_authenticated:
        update_form = UpdateProfileForm(request.POST or None, instance=request.user)
        if update_form.is_valid():
            profile_instance = update_form.save(commit=False)
            profile_instance.first_name = request.POST.get('first_name')
            profile_instance.last_name = request.POST.get('last_name')
            profile_instance.save()
            messages.success(request, "You profile details updated successfully.")
            return redirect("account:account-home")
    else:
        messages.warning(request, "Please Login. You cannot access this page!")
        return redirect("account:login")

    context = {
        'update_form': update_form,
    }
    return render(request, "accounts/account-profile.html", context=context)

accounts/templates/accounts/account-home.html
{% extends 'base.html' %}

{% block title %} Account Home {% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-12 d-flex flex-wrap">
            <h2>Account : {% if request.user.first_name %} {{ request.user.first_name }} {{ request.user.last_name }}
                {% else %} {{ request.user }} {% endif %}</h2>
            {% if request.user.is_superuser %}
            <div class="btn-toolbar mb-2 mb-md-0 ml-auto">
                <button type="button" class="btn btn-sm btn-outline-secondary ">
                    <span data-feather="calendar"></span>
                    Superuser Account - Admin <i class="fas fa-user-cog fa-lg ml-1"></i>
                </button>
            </div>
            {% endif %}
        </div>

        <div class="col-12">
            <hr>
        </div>

        <div class="col-12 col-md-3 my-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Support</h5>
                    <div class="list-group">
                        <a href="{% url 'contact' %}" class="list-group-item">Contact Us</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-12 col-md-3 my-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Billing</h5>
                    <div class="list-group">
                        <a href="{% url 'account:order_history' %}" class="list-group-item">Recent Orders</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-12 col-md-3 my-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Account Details</h5>
                    <div class="list-group">
                        <a href="{% url 'account:update_profile' %}" class="list-group-item">Update Your Profile</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-12 col-md-3 my-3 ">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">History</h5>
                    <div class="list-group">
                        <a href="{% url 'account:user_history' %}" class="list-group-item">Product Viewed</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-12">
            <hr>
        </div>

        {% if request.user.is_superuser %}
        <div class="col-12 col-md-3 my-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Analytics</h5>
                    <div class="list-group">
                        <a href="{% url 'this-week-sales-analytics' %}" class="list-group-item">Sales</a>
                        <a href="{% url 'product-advertisement' %}" class="list-group-item">Advertise Product</a>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}

    </div>
</div>

{% endblock %}

accounts/templates/accounts/account-profile.html
{% extends 'base.html' %}

{% block title %} Account Profile: {{ request.user }} {% endblock %}

{% block content %}

<div class="container">
    <form method="POST">
        {% csrf_token %}
        <div class="text-center form-group mb-4">
            <h1 class="h2 mb-3 font-weight-normal">Update Your Account Details</h1>
        </div>
        <div class="col-sm-5 col-12 form-group mx-auto">
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" class="form-control" id="username" value="{{ request.user.username }}" disabled
                aria-describedby="UserHelp">
                <small id="UserHelp" class="form-text text-muted">You cannot edit this field.</small>
            </div>
            {{ update_form.as_p }}
            <div class="form-group">
                <label for="email">Email address</label>
                <input type="text" class="form-control" id="email" value="{{ request.user.email }}" disabled
                    aria-describedby="emailHelp">
                <small id="emailHelp" class="form-text text-muted">You cannot edit this field.</small>
            </div>
            <button class="btn btn-lg btn-primary btn-block mt-2" type="submit">Update</button>
        </div>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Login Page {% endblock %}

{% block content %}
<div class="container">
    <form method="POST"> {% csrf_token %}
        <div class="text-center form-group mb-4">
            <img class="mb-4" src="{% static 'imgs/login.png' %}"
                alt="Contact Us" width="150" height="150">
            <h1 class="h2 mb-3 font-weight-normal">{{ title }}</h1>
        </div>
        <div class="col-sm-5 col-12 form-group mx-auto">
            {{ form }}
            <button class="btn btn-lg btn-primary btn-block mt-2" type="submit">Login</button>
        </div>
    </form>
    <p class="mt-5 mb-3 text-center text-muted">Don't have an account? <a href="{% url 'account:register' %}">Sign up here</a></p>
</div>

{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Registration Page {% endblock %}

{% block content %}
<div class="container">
    <form method="POST"> {% csrf_token %}
        <div class="text-center form-group mb-4">
            <img class="mb-4" src="{% static 'imgs/register.png' %}"
                alt="Contact Us" width="150" height="150">
            <h1 class="h2 mb-3 font-weight-normal">{{ title }}</h1>
        </div>
        <div class="col-sm-5 col-12 form-group mx-auto">
            {{ form }}
            <button class="btn btn-lg btn-primary btn-block mt-2" type="submit">Register</button>
        </div>
    </form>
    <p class="mt-5 mb-3 text-center text-muted">Already have an account? <a href="{% url 'account:login' %}">Sign in here</a></p>
</div>

{% endblock %}