accounts/urls.py
from django.urls import path

from .views import account_home_page, login_page, logout_page, register_page, address_create_view, update_profile
from orders.views import order_history_page
from analytics.views import user_product_history

app_name = 'account'

urlpatterns = [
    path('home/', account_home_page, name='account-home'),
    path('login/', login_page, name='login'),
    path('logout/', logout_page, name='logout'),
    path('register/', register_page, name='register'),
    path('address/create/view/', address_create_view, name='address_create_view'),
    path('order/history', order_history_page, name='order_history'),
    path('user/history', user_product_history, name='user_history'),
    path('user/profile/update/', update_profile, name='update_profile'),
]

carts/urls.py
from django.urls import path

from .views import cart_home, cart_update, checkout_home, checkout_success, payment_page_view

app_name = 'cart'

urlpatterns = [
    path('', cart_home, name='home'),
    path('update/', cart_update, name='update'),
    path('checkout/', checkout_home, name='checkout'),
    path('success/', checkout_success, name='success'),
    path('payment/online/', payment_page_view, name='payment_page'),

]

eComm/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from .views import home_page, contact_page
from products.views import search_product 
from analytics.views import (
    sales_view, 
    sales_ajax_view, 
    last_week_sales_view, 
    three_week_sales_view, 
    four_week_sales_view,
    product_analytics_view, 
    customers_analytics_view, 
    advertise_product_view
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name='home'),
    path('contact/', contact_page, name='contact'),
    path('search/', search_product, name='search'),
    path('products/', include('products.urls', namespace='products')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='order')),
    path('account/', include('accounts.urls', namespace='account')),
    path('analytics/sales/this-week/', sales_view, name="this-week-sales-analytics"),
    path('analytics/sales/last-week/', last_week_sales_view, name="last-week-sales-analytics"),
    path('analytics/sales/three-weeks-ago/', three_week_sales_view, name="three-week-sales-analytics"),
    path('analytics/sales/four-week-ago/', four_week_sales_view, name="four-week-sales-analytics"),
    path('analytics/sales/data/', sales_ajax_view, name="sales-analytics-data"),
    path('analytics/sales/products/', product_analytics_view, name="product-analytics"),
    path('analytics/sales/customer/', customers_analytics_view, name="customer-analytics"),
    path('analytics/sales/product-advertisement/', advertise_product_view, name="product-advertisement"),

]

if settings.DEBUG :
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from .views import product_list, product_detail 

app_name = 'products'

urlpatterns = [
    path('', product_list, name='product-list'),
    path('<str:slug>/', product_detail, name='product-detail'),

]

templates/base.html
<!doctype html>
<html lang="en">
{% load static %}

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">

    <!-- Font-awesome CSS CDN  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">

    <!-- Custom CSS  -->

    <title>{% block title %} {% endblock %}</title>
</head>

<body>

    <!-- navbar  -->
    {% include 'navbar.html' %}

    <!-- message bar  -->
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <strong>Message: </strong>{{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endfor %}

    {% block content %}

    {% endblock %}


    <!-- footer  -->
    {% include 'footer.html' %}



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="{% static 'bootstrap/js/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Chart.js CDN -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>

    <!-- Custom JavaScript -->
    {% block JavaScript %}   {% endblock %}
    
</body>

</html>

templates/contact_page.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Contact Page {% endblock %}

{% block content %}
<div class="container">
    <form method="POST"> {% csrf_token %}
        <div class="text-center form-group mb-4">
            <img class="mb-4" src="{% static 'imgs/contact.png' %}"
                alt="Contact Us" width="150" height="165">
            <h1 class="h2 mb-3 font-weight-normal">{{ title }}</h1>
            <p>{{ content }}</p>
        </div>
        <div class="col-sm-6 col-12 form-group mx-auto">
            {{ form }}
            <button class="btn btn-lg btn-primary btn-block mt-2" type="submit">Submit</button>
        </div>
    </form>
</div>
{% endblock %}

templates/footer.html
<style>
    .footer-link {
        color: white;
    }
    
    .page-footer {
        background-color: #222222;
        padding-top: 100px;
        color: white;
    }
    
    #footer-hr {
        background-color: white;
    }
</style>

<!-- Footer -->
<footer class="page-footer pt-4">
    <div class="container-fluid text-center">
        <!-- Grid row -->
        <div class="row p-5">

            <!-- Grid column 1 -->
            <div class="col-lg-4 col-md-6 col-sm-6 p-3">
                <div>
                    <h3>Rauf-eComm Website</h3>

                    <p>
                        <a class="footer-link" href="{% url 'home' %}">Home</a> -
                        <a class="footer-link" href="{% url 'contact' %}">Contact</a> -
                        <a class="footer-link" href="{% url 'products:product-list' %}">Products</a>
                    </p>

                    <p>Rauf-eComm Website &copy; 2021</p>
                </div>

            </div>
            <!-- Grid column -->

            <!-- Grid column 2 -->
            <div class="col-lg-4 col-md-6 col-sm-6 p-3">
                <div class="row">
                    <div class="col-4 text-right">
                        <i class="fa fa-map-marker fa-lg"></i>
                    </div>
                    <div class="col-8 text-left">
                        <p>Adejumo Ibadan, Nigeria</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-4 text-right">
                        <i class="fa fa-phone fa-lg"></i>
                    </div>
                    <div class="col-8 text-left">
                        <p>+234 8110845095, +234 9045816857</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-4 text-right">
                        <i class="fa fa-envelope fa-lg"></i>
                    </div>
                    <div class="col-8 text-left">
                        <p><a class="footer-link" href="mailto:omotosoabiola9525@gmail.com">omotosoabiola9525@gmail.com</a></p>
                    </div>
                </div>

            </div>
            <!-- Grid column -->

            <!-- Grid column 3 -->
            <div class="col-lg-4 col-md-6 col-sm-6 p-3">
                <h5>About the company</h5>
                <p>We Are Here To Provide You The Best Experiance of eCommerce Website.<br><i><u>Feel Free To Buy
                            Anything.</u></i></p>

                <div>
                    <a class="footer-link" href="https://www.facebook.com/chetan.bhogade.3"><i class="fab fa-facebook-f fa-lg p-1"></i></a>
                    <a class="footer-link" href="https://twitter.com/BhogadeChetan"><i class="fab fa-twitter fa-lg p-1"></i></a>
                    <a class="footer-link" href="https://www.instagram.com/chetan_bhogade/"><i class="fab fa-instagram fa-lg p-1"></i></a>
                    <a class="footer-link" href="https://github.com/ChetanBhogade"><i class="fab fa-github fa-lg p-1"></i></a>
                </div>

            </div>
            <!-- Grid column -->
        </div>
        <!-- Grid row -->
    </div>

    <!-- Copyright -->
    <hr id="footer-hr">

    <div class="footer-copyright text-center py-3">© 2020-2021 Copyright:
        <a class="footer-link" href="{% url 'home' %}"> Rauf-eComm Website </a>
    </div>
    <!-- Copyright -->

</footer>
<!-- Footer -->

templates/home_page.html
{% extends 'base.html' %} {% load static %} {% block title %} Rauf-eComm {% endblock %} {% block content %}

<style>
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
    }
    
    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
    }
    /* CUSTOMIZE THE CAROUSEL
  -------------------------------------------------- */
    /* Carousel base class */
    
    .carousel {
        margin-bottom: 4rem;
    }
    /* Since positioning the image, we need to help out the caption */
    
    .carousel-caption {
        bottom: 3rem;
        z-index: 10;
    }
    /* Declare heights because of positioning of img element */
    
    .carousel-item {
        height: 32rem;
    }
    
    .carousel-item>img {
        position: absolute;
        top: 0;
        left: 0;
        min-width: 100%;
        height: 32rem;
    }
    /* MARKETING CONTENT
  -------------------------------------------------- */
    /* Center align the text within the three columns below the carousel */
    
    .marketing .col-lg-4 {
        margin-bottom: 1.5rem;
        text-align: center;
    }
    
    .marketing h2 {
        font-weight: 400;
    }
    
    .marketing .col-lg-4 p {
        margin-right: .75rem;
        margin-left: .75rem;
    }
    /* Featurettes
  ------------------------- */
    
    .featurette-divider {
        margin: 5rem 0;
        /* Space out the Bootstrap <hr> more */
    }
    /* Thin out the marketing headings */
    
    .featurette-heading {
        font-weight: 300;
        line-height: 1;
        letter-spacing: -.05rem;
    }
    
    .featurette-image {
        margin-top: 7rem;
    }
    /* RESPONSIVE CSS
  -------------------------------------------------- */
    
    @media (min-width: 40em) {
        /* Bump up size of carousel content */
        .carousel-caption p {
            margin-bottom: 1.25rem;
            font-size: 1.25rem;
            line-height: 1.4;
        }
        .featurette-heading {
            font-size: 50px;
        }
        .featurette-image {
            margin-top: 7rem;
        }
    }
    
    @media (min-width: 62em) {
        .featurette-heading {
            margin-top: 7rem;
        }
    }
</style>

<main role="main">

    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'imgs/Echo-Dot.jpg' %}" class="d-block w-100">
                <div class="container">
                    <div class="carousel-caption text-left">
                        <h1>Rauf-eComm - Shopping rediscovered.</h1>
                        <p>“When you see it online and you can’t stop thinking about it… Order it and have it delivered to you. Don’t overthink it, just do it!”</p>
                        <p><a class="btn btn-lg btn-primary" href="{% url 'products:product-list' %}" role="button">View
								All Products</a></p>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'imgs/carousal2.jpg' %}" class="d-block w-100">
                <div class="container">
                    <div class="carousel-caption">
                        <h1>The greatest journey of online shop.</h1>
                        <p>“I love shopping. There is a little bit of magic found in buying something new. It is instant gratification, a quick fix.”</p>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'imgs/FT_Allnighters_DB.jpg' %}" class="d-block w-100">
                <div class="container">
                    <div class="carousel-caption text-right">
                        <p><a class="btn btn-light btn-lg " href="/products/fastrack-all-nighters-white/" role="button">View Product</a></p>
                    </div>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>


    <div class="container marketing">

        <!-- My info section -->
        <section>
            <div class="container">
                <div class="row shadow p-3 mb-5 bg-white rounded">
                    <!-- single features -->
                    <div class="col-lg-3 col-md-6 col-sm-6 text-center">
                        <i class="fas fa-truck fa-2x p-3"></i>
                        <h6>Quick Delivery</h6>
                        <p>Faster than you can imagine</p>
                    </div>
                    <!-- single features -->
                    <div class="col-lg-3 col-md-6 col-sm-6 text-center">
                        <i class="fas fa-undo-alt fa-2x p-3"></i>
                        <h6>Return Policy</h6>
                        <p>Returns available on all order</p>
                    </div>
                    <!-- single features -->
                    <div class="col-lg-3 col-md-6 col-sm-6 text-center">
                        <i class="fas fa-headset fa-2x p-3"></i>
                        <h6>24/7 Support</h6>
                        <p>Keeping You Always Connected</p>
                    </div>
                    <!-- single features -->
                    <div class="col-lg-3 col-md-6 col-sm-6 text-center">
                        <i class="fas fa-money-check fa-2x p-3"></i>
                        <h6>Secure Payment</h6>
                        <p>100% Secure Purchase Payment</p>
                    </div>
                </div>
            </div>
        </section>

        <!-- End My Info Section -->

        <hr class="featurette-divider">

        <!-- My Album -->
        <div class="container">
            <div class="row">
                {% for prod in Products %}
                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm">
                        <div class="embed-responsive embed-responsive-1by1">
                            <a href="{{ prod.get_absolute_url }}"><img alt="{{ prod.title }}" class="card-img-top p-2 embed-responsive-item" src="{{ prod.image.url }}" /></a>
                        </div>
                        <div class="card-body">
                            <h4><a style="color: black;" href="{{ prod.get_absolute_url }}">{{ prod.title }}</a></h4>
                            <p class="card-text">{{ prod.description|truncatewords:15 }}</p>
                            <p><b>Price:</b> $ {{ prod.price }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <p><a class="btn btn-sm btn-outline-secondary" href="{{ prod.get_absolute_url }}" role="button">View Product</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

        <!-- End My Album -->

        <!-- START THE FEATURETTES -->

        <hr class="featurette-divider">

        <div class="row featurette shadow-lg p-3">
            <div class="col-md-7">
                <h2 class="featurette-heading">{{ popular_product.title|title }}</h2>
                <h3><span class="text-muted">This Is Our Most Popular Product.</span></h3>
                <p class="lead"><b>Description: - </b> {{ popular_product.description|truncatewords:25 }}</p>
                <p><a class="btn btn-light btn-lg " href="{{ popular_product.get_absolute_url }}" role="button">View Product</a></p>
            </div>
            <div class="col-md-5">
                <img src="{{ popular_product.image.url }}" alt="{{ popular_product.title }}" class="featurette-image img-fluid mx-auto">
            </div>
        </div>

        <hr class="featurette-divider">

        <!-- /END THE FEATURETTES -->


    </div>

</main>

{% endblock %}

templates/navbar.html
{% url 'home' as home_url %} {% url 'contact' as contact_url %} {% url 'account:login' as login_url %} {% url 'account:register' as register_url %} {% url 'account:logout' as logout_url %} {% url 'products:product-list' as products_url %} {% url 'cart:home'
as cart_url %} {% url 'account:account-home' as account_home_url %} {% url 'account:user_history' as user_history_url %}

<nav class="navbar navbar-expand-lg navbar-dark sticky-top mb-3 bg-dark py-1">
    <div class="container">
        <a class="navbar-brand" href="{{ home_url }}">Rauf-eComm</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if request.path == home_url %} active {% endif %}">
                    <a class="nav-link" href="{{ home_url }}">Home</a>
                </li>
                <li class="nav-item {% if request.path == contact_url %} active {% endif %}">
                    <a class="nav-link" href="{{ contact_url }}">Contact</a>
                </li>
                <li class="nav-item {% if request.path == products_url %} active {% endif %}">
                    <a class="nav-link" href="{{ products_url }}">Products</a>
                </li>
                <li class="nav-item {% if request.path == login_url  %} active {% endif %}">
                    <a class="nav-link" href="{{ login_url  }}">New User SignIn</a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="{% url 'account:account-home' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Account
                        </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item {% if request.path == account_home_url %} active {% endif %}" href="{% url 'account:account-home' %}">Account Home</a>
                        <a class="dropdown-item {% if request.path == contact_url %} active {% endif %}" href="{{ contact_url }}">Support</a>
                        <a class="dropdown-item {% if request.path == user_history_url %} active {% endif %}" href="{{ user_history_url }}">History</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{{ logout_url }}">Logout: {{ request.user }}</a>
                    </div>
                </li>
                {% else %}
                <li class="nav-item {% if request.path == login_url %} active {% endif %}">
                    <a class="nav-link" href="{{ login_url }}">Login</a>
                </li>
                <li class="nav-item {% if request.path == register_url %} active {% endif %}">
                    <a class="nav-link" href="{{ register_url }}">Register</a>
                </li>
                {% endif %}
                <li class="nav-item {% if request.path == cart_url %} active {% endif %}">
                    <a class="nav-link" href="{{ cart_url }}">Cart: <i class="fas fa-cart-arrow-down"></i> {{ request.session.cart_items_count }} </a>
                </li>

            </ul>
            {% include 'search/snippets/search-form.html' %}
        </div>
    </div>
</nav>